### ISSUE TITLE
Database connection gets disconnected while tracking too many tables

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1070] opened 2020-06-11 15:42 UTC
While tracking too many tables at once, the database reports too many connections and the connection with database gets dropped. 

Seems as if Space Cloud is making a new connection while tracking a table. Chances are these multiple connections happen because of errors that space cloud encounters while tracking certain tables. These errors can be due to tracking tables that contains types not supported by space cloud

**Comment by YourTechBud** [comment] 2020-06-19 06:35
@HeyItsJs on which version was this bug encountered?

I went through the code, the problem is not that we are leaving connections open. I think Mission Control is sending the inspect commands for all tables at once. We should limit the max connections on the driver

**Comment by YourTechBud** [comment] 2020-06-20 09:55
The problems seems to be from the fact that MySQL doesnt close stale connections. The golang driver registers it as closed, but mysql doesn't seem to close the threads.

As a work around, I am preventing reconnecting to MySQL on every call to `crud.SetConfig` as long as the connection details remain the same. The problem will show up again if the connection string changes often.

However, MySQL will automatically close the orphaned connections once the [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) is hit.

**Comment by sharadregoti** [comment] 2020-06-20 11:41
@YourTechBud should we close this issue?

**Comment by YourTechBud** [comment] 2020-06-20 11:46
Yes

**Closed by YourTechBud** 2020-06-20 11:46 UTC
Labels: backend, p/high, 🐛 bug
