### ISSUE TITLE
space-cli setup command should remove all created resources if the setup wasn't successfull 

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1149] opened 2020-07-09 06:55 UTC
I was trying the following command:

```bash
space-cli setup --dev --config ../gateway/config.yaml
```

Which gave me an error:

```bash
ERRO[0002] Unable to create container (space-cloud-gateway)  error="Error response from daemon: invalid mount config for type \"bind\": invalid mount path: '../gateway/config.yaml' mount path must be absolute"
```

This is alright. Since I should have provided an absolute path. But then when I try the command once again with the absolute path, I get this error, which is not okay:

```bash
ERRO[0001] Network (space-cloud) already exists, try using different cluster  error=
```

`space-cli setup` command should have performed cleanup process (e.g. removing the network) on getting any error in setup, so that next time we can do a fresh setup. 

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment] 2020-07-09 06:59
@sharadregoti you can discuss what all things need to be cleaned up with @YourTechBud if you want. 

Also, as a heads up, don't throw unnecessary logs in the cleanup process. For example, it might be possible that we are creating 10 resources in setup. But due to error, only 1 was created. And then in the cleanup, you might try to remove all the 10. While doing so, ensure that you don't log that the other 9 things that you are trying to remove don't exist.

**Comment by HeyItsJs** [comment] 2020-07-09 07:00
As a side note, why is the `error=` field empty in the second error log that I provided above? @sharadregoti

**Comment by YourTechBud** [comment] 2020-07-18 10:27
Duplicate of #1090

**Closed by YourTechBud** 2020-07-18 10:27 UTC
Labels: backend, 🐛 bug
