### ISSUE TITLE
How to disable auth(or use as lib)?

### ISSUE THREAD

**Issue by koolay** [spaceuptech/space-cloud#1181] opened 2020-07-31 10:25 UTC
### The problem faced currently?
We want to use the gateway and ignore auth.

```go 
       // how to ignore this checking
	actions, _, err := graph.auth.IsReadOpAuthorised(ctx, graph.project, dbAlias, col, token, req)
```
### How can we solve it?

Be `space-cloud` able to use as lib for compile graphql to sql of diffrent db(mysq、pg、mongo) ?

**Comment by YourTechBud** [comment] 2020-07-31 13:28
@koolay are you referring to using gateway as an *embedded* library? If so, you can simply mock the `auth` module since thats an interface. Thats would be the easier way to do that.

If you want to use it as a standalone server, you can simply set a default read rule to allow.

**Comment by koolay** [comment] 2020-07-31 13:37
@YourTechBud 
Thanks, I will try it.

**Comment by YourTechBud** [comment] 2020-07-31 14:29
Closing this since the issue is resolved

**Closed by YourTechBud** 2020-07-31 14:29 UTC

**Comment by koolay** [comment] 2020-08-03 02:54
@YourTechBud 

Hi, YourTechBud,   `graphql.Module`  depency `auth.Module` not  `interface` . 

```go
package graphql

type Module struct {
	project   string
	auth      *auth.Module   // not a interface
	crud      *crud.Module   // not a interface
	functions *functions.Module
	schema    *schema.Schema
}

// New creates a new GraphQL module
func New(a *auth.Module, c *crud.Module, f *functions.Module, s *schema.Schema) *Module {
	return &Module{auth: a, crud: c, functions: f, schema: s}
}
```

**Comment by YourTechBud** [comment] 2020-08-03 05:11
@koolay, sorry for the misinformation. We have made it an interface in the `v0.19.0` branch. You can check that branch out and make changes accordingly.

If waiting is an option, we'll be releasing `0.19.0` soon enough. With a week or so.

**Comment by koolay** [comment] 2020-08-03 05:14
@YourTechBud 
Thanks, very nice.
