### ISSUE TITLE
The problem still there "Unable to create container (space-cloud-gateway)"

### ISSUE THREAD

**Issue by turnerguo** [spaceuptech/space-cloud#1355] opened 2020-10-09 03:37 UTC
### Describe the bug

Run setup command received errors.

### Expected behaviour

Expected setup successfully!

### Actual behaviour 

Run `./space-cli setup --dev` receive errors:
```zsh
INFO[0000] Setting up Space Cloud on docker.
INFO[0000] Fetching latest Space Cloud Version
INFO[0006] Starting container space-cloud-gateway...
INFO[0006] Image spaceuptech/gateway:0.19.4 does not exist. Need to pull it from Docker Hub. This may take some time.
INFO[0240] Image spaceuptech/gateway:0.19.4 already exists. No need to pull it again
INFO[0240] Destroying the cluster (default)...
INFO[0240] Space cloud cluster has been destroyed successfully ð¢
INFO[0240] Looking forward to seeing you again! ð
ERRO[0240] Unable to create container (space-cloud-gateway)  error="Error response from daemon: No such image: spaceuptech/gateway:0.19.4"
Error: Unable to create container (space-cloud-gateway)
```
```zsh
➜  space ./space-cli -v
space-cli version 0.19.3
```

### Your environment
- Space Cloud version: 0.19.3
- OS: CentOS Linux release 7.8.2003 (Core) 
- Kubernetes or Docker: Docker version 19.03.11, build 42e35e61f3
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by turnerguo** [comment] 2020-10-09 06:01
The `spaceuptech/runner:0.19.4` image also can not able to download:
```bash
➜ docker pull spaceuptech/runner:0.19.4
Error response from daemon: Get https://registry-1.docker.io/v2/spaceuptech/runner/manifests/0.19.4: Get https://auth.docker.io/token?scope=repository%3Aspaceuptech%2Frunner%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

 The `https://registry-1.docker.io/v2/spaceuptech/runner/manifests/0.19.4` url returns:
```json
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"spaceuptech/runner","Action":"pull"}]}]}
```

**Comment by YourTechBud** [comment] 2020-10-11 11:43
Unable to reproduce this. @sharadregoti @HeyItsJs Can you guys see if you are able to reproduce this?

@turnerguo Can you try pulling the images manually once:
```sh
docker pull spaceuptech/gateway:0.19.5
docker pull spaceuptech/runner:0.19.5
space-cli setup --dev --version 0.19.5
```

**Comment by HeyItsJs** [comment] 2020-10-11 13:04
Even I wasn't able to reproduce it. @turnerguo @YourTechBud. Pulling images manually as @YourTechBud might help.

**Comment by turnerguo** [comment] 2020-10-14 09:02
It works right now... I guess it maybe docker hub issue.
<img width="887" alt="image" src="https://user-images.githubusercontent.com/633880/95966680-0041b700-0e3e-11eb-84f4-a36fad846af7.png">
Is that `xxx uses outdated schema1 manifest format.` causes such problem? or docker hub getting confused sometime...

But, when I try setup space it still tell me the auth issue, I guess the space-cli made some special scripts/magic inside? 
```
INFO[0000] Setting up Space Cloud on docker.
INFO[0000] Fetching latest Space Cloud Version
INFO[0006] Starting container space-cloud-gateway...
INFO[0006] Image spaceuptech/gateway:0.19.5 does not exist. Need to pull it from Docker Hub. This may take some time.
ERRO[0049] Unable to pull public image with id (spaceuptech/gateway:0.19.5) - Error response from daemon: Get https://registry-1.docker.io/v2/spaceuptech/gateway/manifests/0.19.5: Get https://auth.docker.io/token?scope=repository%3Aspaceuptech%2Fgateway%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
INFO[0049] Destroying the cluster (default)...
INFO[0049] Space cloud cluster has been destroyed successfully ð¢
INFO[0049] Looking forward to seeing you again! ð
ERRO[0049] Could not pull the image (spaceuptech/gateway:0.19.5). Make sure docker is running and that you have an active internet connection.  error=
Error: Could not pull the image (spaceuptech/gateway:0.19.5). Make sure docker is running and that you have an active internet connection.
```
 @HeyItsJs @YourTechBud

**Comment by YourTechBud** [comment] 2020-10-14 09:21
Hey @turnerguo. You pulled the 0.19.4 version. To start a specific version using space cli, simply add the `--version 0.19.4` flag to the setup command.

Space cli doesn't do anything fancy. It just creates some files and mounts them in the containers which would be tricky to do otherwise

**Comment by YourTechBud** [comment] 2020-10-28 03:30
Closing the issue since it has been resolved

**Closed by YourTechBud** 2020-10-28 03:30 UTC
Labels: 🐛 bug
