### ISSUE TITLE
Google cloud storage configuration returns error

### ISSUE THREAD

**Issue by abasse** [spaceuptech/space-cloud#1177] opened 2020-07-26 09:28 UTC
### Describe the bug
I receive following error message when I try to create a storage backend for Google, using the "Load from Space Cloud Secrets (recommended method)"

**-> dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: unexpected end of JSON input**

### Expected behaviour
Should work..

### Steps to reproduce
- Created space cloud secret from Google JSON credential file
- Select secret while creating storage backend for Google

### Your environment
- Space Cloud version: 0.18.4
- OS: OSX
- Kubernetes or Docker: Docker

**Comment by HeyItsJs** [comment] 2020-07-26 09:31
Duplicate of #1165

**Closed by HeyItsJs** 2020-07-26 09:31 UTC

**Comment by HeyItsJs** [comment] 2020-07-26 09:32
Hey @abasse, the workaround for this bug as of now is mentioned in the #1165
