### ISSUE TITLE
schema module bug

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#892] opened 2020-03-30 09:35 UTC
### Describe the bug
While adding a field to a table under certain conditions, I get this error: 
```
pq: constraint "c_test_id" of relation "test" does not exist
``` 

### Steps to reproduce
Create a table `test` with the following schema:

```graphql
type test {
  id: ID! @primary
  name: String
}
```

Then change the schema to this:

```graphql
type test {
  name: String
}
```

Then change the schema to this:

```graphql
type test {
  name: String
  age: Integer
}
```
And you will get the above error.

### Your environment
- Space Cloud version: `v0.17.0`
- OS: Linux
- Database: Postgres

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment] 2020-08-12 18:43
Duplicate of #831

**Closed** 2020-08-12 18:44 UTC
Labels: 🐛 bug
