### ISSUE TITLE
Support auto scaling on the basis of CPU and RAM

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1189] opened 2020-08-01 17:18 UTC
### The problem faced currently?

Currently the deployments module of space cloud auto scales deployments either on the basis of number of parallel requests or the number of requests per second. 

However, many people prefer to scale services on the basis of CPU and/or RAM consumption since its easy to model.

### How can we solve it?

Add support for auto scaling on the basis of CPU and/or RAM as well.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment] 2020-08-12 18:53
Duplicate of #756

**Closed by YourTechBud** 2020-08-12 18:53 UTC
Labels: backend, enhancement, mission-control
