### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#378] opened 2019-08-05 08:23 UTC
### The problem faced currently?
Right now there is no first class support for integrating OAuth (google, facebook, twitter, github signin/signup)  

### How can we solve it?
By adding first class APIs to SC directly to integrate OAuth providers
 
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment] 2020-03-06 05:13
Lets add supports like this in a microservice. Now that we can deploy stuff as well, it will be easy to auto setup things.

**Comment by YourTechBud** [comment] 2020-08-12 19:00
Duplicate of #1112

**Closed by YourTechBud** 2020-08-12 19:00 UTC
Labels: enhancement, help wanted

**Comment by theDemon92** [comment] 2022-01-31 09:19
May be supertokens can be build right into space-cloud since it's also opensource
